### ISSUE TITLE
question about the posterior collapsed issue

### ISSUE THREAD

**Issue by speedcell4** [mingdachen/disentangle-semantics-syntax#1]
Hi~
sorry for asking the question before you actually releasing your code.

I just wonder how do you deal with the posterior collapsed issue. I noticed that you use the word average encoder and the vMF distribution for `y` while using the LSTM encoder and the Gaussian distribution for `z`. Is this the reason you don't need to worry about the posterior collapsed issue? if yes, among these things, the most important part is the vMF distribution?

And by the way, why don't you use LSTM encoder for `y`?

Thanks~

**Comment by mingdachen** [comment]
Hi,

Thanks for your interest! For avoiding posterior collapsed, I think the main reason is that I used a pretty small weight for the KL terms for both vMF and Gaussian distributions, although it has a drawback that the variance became very small (I didn't do much hyperparameter tuning).

For LSTM encoders, I am following the recommendation from [this ICLR paper](https://arxiv.org/pdf/1511.08198.pdf), where they found word averaging performs better than a LSTM encoder on STS tasks, and that's why we assumed word ordering is more related to syntax and thus the word position loss.

**Comment by speedcell4** [comment]
thank you so much~
looking forwarding to seeing your code!

**Comment by speedcell4** [comment]
But then why do you need VAE? if you use "pretty small weight for the KL terms for both vMF and Gaussian distributions", why not just use two simple MLPs to model the `z` and `y` and remove KL terms (this is equivalent to turn these KL terms to 0). I mean just the deterministic version of your model. Have you tried this?

**Comment by mingdachen** [comment]
No, we didn't try this and I think you're right -- we didn't prove the necessity of using VAEs. Personally, I think the reason for why we chose VAE is largely because the neural models as well as the proposed multi-task losses were designed based on the idea of latent variables (i.e. semantic variables and syntactic variables). Performance-wise, I think it may not hurt to drop the KL terms (but I found KL terms helpful in my EMNLP paper, which is about sequence labeling).

**Comment by speedcell4** [comment]
Do you mean this one (https://www.aclweb.org/anthology/D18-1020)?
Yes, I understand VAE works for the semi-supervised task, but disentangle-semantics-syntax is a supervised task.
If you get the experimental results of deterministic version, could you please share me with that?
Thanks~

**Comment by mingdachen** [comment]
Yes, will do.
